name: reviewdog
on:
  - pull_request
jobs:
  actionlint:
    runs-on: ubuntu-latest
    steps:
      - uses: Kesin11/actions-timeline@v2
      - uses: actions/checkout@v4
      - uses: reviewdog/action-actionlint@v1
